# Generated by Django 5.1.2 on 2024-11-14 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alimentacion',
            fields=[
                ('id_alimentacionm', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='alimento/')),
            ],
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id_periodo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=500)),
                ('inicio', models.FloatField()),
                ('fin', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Dinosaurio',
            fields=[
                ('id_dinosaurio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('tamano', models.FloatField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='dinosaurio/')),
                ('descripcion', models.CharField(max_length=500)),
                ('audio_rugido', models.FileField(upload_to='rugido/')),
                ('alimenatacion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dinoteca.alimentacion')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dinoteca.periodo')),
            ],
        ),
    ]
