# Generated by Django 5.1.2 on 2024-11-25 23:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Foro',
            fields=[
                ('id_foro', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='Nuevo Foro', max_length=150)),
                ('descripcion', models.CharField(blank=True, max_length=600, null=True)),
                ('participantes', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id_mensaje', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(default='Nuevo mensaje', max_length=150)),
                ('mensaje', models.CharField(max_length=600)),
                ('foro', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='foros.foro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
