# Generated by Django 5.1.2 on 2024-11-26 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foro',
            name='codigo',
            field=models.CharField(default='No-code', max_length=15),
        ),
    ]
